
name: MI-RM2100

on: 
  workflow_dispatch:

#设置仓库的读写权限
permissions:
  contents: write
env:
  TZ: Asia/Shanghai
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt-get update
        sudo apt-get -y install unzip libtool-bin curl cmake gperf gawk flex bison nano xxd fakeroot \
        cpio git python3-docutils gettext automake autopoint texinfo build-essential help2man \
        pkg-config zlib1g-dev libgmp3-dev libmpc-dev libmpfr-dev libncurses5-dev libltdl-dev wget
    - name: Install UPX
      uses: crazy-max/ghaction-upx@v3
      with:
        version: v4.2.4
        install-only: true
    - name: Clone source code
      env:
        KERNEL: 3.4
      run: |
        git clone --depth=1 https://github.com/${GITHUB_REPOSITORY}.git /opt/rt-n56u
        cd /opt/rt-n56u/toolchain-mipsel
        sh dl_toolchain.sh
        mkdir -p /opt/images/
        
        ##### 修改内存空间和 storage空间13m
        sed -i 's/SIZ=0x0400000/SIZ=0x0d00000/g' /opt/rt-n56u/trunk/configs/boards/RM2100/kernel-3.4.x-5.0.config
        sed -i 's/size_etc="6M"/size_etc="13M"/g' /opt/rt-n56u/trunk/user/scripts/dev_init.sh
        sed -i 's/size_tmp="24M"/size_tmp="30M"/g' /opt/rt-n56u/trunk/user/scripts/dev_init.sh
        sed -i 's/mtd_part_size=65536/mtd_part_size=13631488/g' /opt/rt-n56u/trunk/user/scripts/mtd_storage.sh
    - name: Build Firmware
      env:
        TNAME: RM2100
        KERNEL: 3.4
      run: |
        cd /opt/rt-n56u/trunk
        if [ ! -f configs/templates/$TNAME.config ] ; then
        echo "configs/templates/$TNAME.config 没有找到 "
        exit 1
        fi
        cp -f configs/templates/$TNAME.config .config
        sed -i 's/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=n/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE=y/g' .config
        ################################################################################################
        ###  清除默认配置###
        sed -i '/CONFIG_FIRMWARE_ENABLE_IPV6/d' .config
        sed -i '/CONFIG_FIRMWARE_ENABLE_USB/d' .config
        sed -i '/CONFIG_FIRMWARE_ENABLE_UFSD/d' .config
        sed -i '/CONFIG_FIRMWARE_ENABLE_FAT/d' .config
        sed -i '/CONFIG_FIRMWARE_ENABLE_EXFAT/d' .config
        sed -i '/CONFIG_FIRMWARE_ENABLE_EXT2/d' .config
        sed -i '/CONFIG_FIRMWARE_ENABLE_EXT3/d' .config
        sed -i '/CONFIG_FIRMWARE_ENABLE_EXT4/d' .config
        sed -i '/CONFIG_FIRMWARE_ENABLE_XFS/d' .config
        sed -i '/CONFIG_FIRMWARE_ENABLE_FUSE/d' .config
        sed -i '/CONFIG_FIRMWARE_ENABLE_SWAP/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_UVC/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_HID/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SERIAL/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_AUDIO/d' .config

        sed -i '/CONFIG_FIRMWARE_INCLUDE_XFRM/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_QOS/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_IMQ/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_IFB/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_IPSET/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NFSD/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NFSC/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_CIFS/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NTFS_3G/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_LPRD/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_U2EC/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TCPDUMP/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_HDPARM/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_PARTED/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SMBD/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SMBD36/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_WINS/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SMBD_SYSLOG/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FTPD/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_RPL2TP/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_EAP_PEAP/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DDNS_SSL/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_HTTPS/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SFTP/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DROPBEAR/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DROPBEAR_FAST_CODE/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_OPENSSH/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_OPENVPN/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SSWAN/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EC/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_OPENSSL_EXE/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_XUPNPD/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MINIDLNA/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FIREFLY/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FFMPEG_NEW/d' .config

        
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TRANSMISSION/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TRANSMISSION_WEB_CONTROL/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ARIA/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ARIA_WEB_CONTROL/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_CURL/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SCUTCLIENT/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_GDUT_DRCOM/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DOGCOM/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MINIEAP/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NJIT_CLIENT/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NAPT66/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SSSERVER/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DNSFORWARDER/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_VLMCSD/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TTYD/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_LRZSZ/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_HTOP/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NANO/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_IPERF3/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_DUMP1090/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_RTL_SDR/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MTR/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SOCAT/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SRELAY/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_MENTOHUST/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPC/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_FRPS/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TUNSAFE/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_WIREGUARD/d' .config   
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ZEROTIER/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_ALIDDNS/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SHADOWSOCKS/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_V2RAY/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_XRAY/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_TROJAN/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_SSOBFS/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_NPC/d' .config
        sed -i '/CONFIG_FIRMWARE_WEBUI_HIDE_VPN/d' .config
        sed -i '/CONFIG_FIRMWARE_INCLUDE_OPENVPN/d' .config
        # 清除默认配置结束
        ######################################################################
        #以下选项是定义你需要的功能，（y=集成,n=忽略），重新写入到.config文件
        ######################################################################
        ##系统组件
        #启用 IPv6 支持
        echo "CONFIG_FIRMWARE_ENABLE_IPV6=y" >> .config

        #隐藏VPN web ui
        echo "CONFIG_FIRMWARE_WEBUI_HIDE_VPN=y" >> .config
              
        ##下载工具 curl 必备
        echo "CONFIG_FIRMWARE_INCLUDE_CURL=y" >> .config
   
         ## IPV6中继
        echo "CONFIG_FIRMWARE_INCLUDE_NAPT66=y" >> .config

         ## 系统状态监控工具
        echo "CONFIG_FIRMWARE_INCLUDE_HTOP=y" >> .config

         ## 文本编辑器
        echo "CONFIG_FIRMWARE_INCLUDE_NANO=y" >> .config

         ## iperf3测速软件
        echo "CONFIG_FIRMWARE_INCLUDE_IPERF3=y" >> .config

        ## ipv6端口转发工具
        echo "CONFIG_FIRMWARE_INCLUDE_SOCAT=y" >> .config
        #########################################################################################
        sudo ./clear_tree
        sudo ./build_firmware_modify $TNAME 0
        sudo mv -f images/*.trx /opt/images/
        cp -f .config /opt/images/${TNAME}.config
        echo "build_time=$(date '+%Y年%m月%d日%H:%M:%S' | jq -sRr @uri)" >> $GITHUB_ENV
        echo "tag=$(date '+%Y-%m-%d')" >> $GITHUB_ENV
    - name : Upload packages
      uses: actions/upload-artifact@master
      if: always()
      with:
        name: MI-RM2100
        path: /opt/images

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        body: |
           > ### ![](https://img.shields.io/badge/%E7%BC%96%E8%AF%91%E6%97%B6%E9%97%B4-${{ env.build_time }}-8267?logo=github&labelColor=%E9%A1%BB)![](https://img.shields.io/github/downloads/${{ github.repository }}/${{ env.tag }}/total?label=%E4%B8%8B%E8%BD%BD%E6%AC%A1%E6%95%B0&logo=github)

           `型号.config` 是集成的插件模板
           
        tag_name: ${{ env.tag }}
        files: /opt/images/*
